version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productdb:27017"
    depends_on:
      - productdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=redisdb:6379"
    depends_on:
      - redisdb
    ports:
      - "8001:80"

